modLoader = "javafml"
loaderVersion = "[38,)"
license = "Apache-2.0"

[[mods]]
modId = "forgedapi"
version = "${version}"
displayName = "ForgedAPI"
displayURL="https://github.com/PortingLab/ForgedAPI" #optional
logoFile= "icon.png" #optional
credits="FabricMC" #optional
authors="PortingLab" #optional
description = '''
Fabric API unofficial Forge port.

Re-implement part of the Fabric API on Forge.
'''

[[dependencies.forgedapi]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgedapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
