modLoader = "javafml"
loaderVersion = "[36,)"
license = "Apache-2.0"

[[mods]]
modId = "forgedapi"
version = "${version}"
displayName = "ForgedAPI"
displayURL="https://github.com/PortingLab/ForgedAPI"
credits="FabricMC"
authors="PortingLab"
description = '''
Fabric Lifecycle Events unofficial Forge port.
'''

[[dependencies.forgedapi]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgedapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
